spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org: DEBUG

# todo должна быть один файл с пропертями, а у тебя два
