spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jackson:
    date-format: org.openapitools.swaggerapi.utils.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org: ERROR


